
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';

export const GET_BASKETS_SUCCESS = 'GET_BASKETS_SUCCESS';
export const ADD_BASKET_SUCCESS = 'ADD_BASKET_SUCCESS';
export const DELETE_BASKET_SUCCESS = 'DELETE_BASKET_SUCCESS';


export const LOAD_SEARCH_LAYOUT = 'LOAD_SEARCH_LAYOUT';
