
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';

export const GET_LESKAS_SUCCESS = 'GET_LESKAS_SUCCESS';
export const DELETE_LESKA_SUCCESS = 'DELETE_LESKA_SUCCESS';

export const GET_BASKETS_SUCCESS = 'GET_BASKETS_SUCCESS';
export const DELETE_BASKET_SUCCESS = 'DELETE_BASKET_SUCCESS';


export const LOAD_SEARCH_LAYOUT = 'LOAD_SEARCH_LAYOUT';
